name: Move Issues to Done Column by Date

on:
  schedule:
    - cron: '0 16 * * *' # Exécute tous les jours à 16h
  workflow_dispatch:

jobs:
  move_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Get Done Column ID
        id: get_column_id
        run: |
          DONE_COLUMN_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                               -H "Accept: application/vnd.github.v3+json" \
                               https://api.github.com/projects/YOUR_PROJECT_ID/columns | \
                               jq -r '.[] | select(.name=="Terminé") | .id')
          echo "DONE_COLUMN_ID=$DONE_COLUMN_ID" >> $GITHUB_ENV

      - name: Create move_issues.mjs
        run: |
          echo "import { Octokit } from '@octokit/rest';
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function moveIssues() {
            console.log('Fetching issues...');
            const issues = await octokit.issues.listForRepo({
              owner: process.env.GITHUB_OWNER,
              repo: process.env.GITHUB_REPO,
              state: 'open'
            });

            console.log('Issues fetched:', issues.data.length);
            const today = new Date();
            for (const issue of issues.data) {
              console.log('Processing issue:', issue.number);
              const match = issue.body.match(/Date de fermeture: (\d{4}-\d{2}-\d{2})/);
              if (match) {
                const closeDate = new Date(match[1]);
                console.log('Close date:', closeDate);
                if (closeDate < today) {
                  console.log('Moving issue to Done column:', issue.number);
                  await octokit.projects.moveCard({
                    card_id: issue.id,
                    column_id: process.env.GITHUB_DONE_COLUMN_ID,
                    position: 'top'
                  });
                }
              }
            }
          }

          moveIssues();" > move_issues.mjs

      - name: Run move_issues.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: 'Exo-create'
          GITHUB_REPO: 'Classe-Informatique-I.FDA-P1A-'
          GITHUB_DONE_COLUMN_ID: ${{ env.DONE_COLUMN_ID }}
        run: node move_issues.mjs
