
name: Update Issues by Date TEST

on:
#   schedule:
#     # - cron: '0 16 * * *' # Exécute tous les jours à 16h
  workflow_dispatch:

jobs:
  update_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Create update_issues.mjs
        run: |
          echo "import { Octokit } from '@octokit/rest';
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function updateIssues() {
            console.log('Récupération des issues...');
            const issues = await octokit.issues.listForRepo({
              owner: process.env.GITHUB_OWNER,
              repo: process.env.GITHUB_REPO,
              state: 'open'
            });

            console.log('Issues récupérées:', issues.data.length);
            const today = new Date();
            for (const issue of issues.data) {
              console.log('Traitement de l\'issue:', issue.number);
              const match = issue.body.match(/Date de fermeture: (\d{4}-\d{2}-\d{2})/);
              if (match) {
                const closeDate = new Date(match[1]);
                console.log('Date de fermeture:', closeDate);
                if (closeDate < today) {
                  console.log('Mise à jour de l\'issue:', issue.number);
                  await octokit.projects.updateCard({
                    card_id: issue.project_card_id,
                    note: 'Terminé'
                  });
                }
              }
            }
          }

          updateIssues();" > update_issues.mjs

      - name: Run update_issues.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: 'Exo-create'
          GITHUB_REPO: 'Classe-Informatique-I.FDA-P1A-'
        run: node update_issues.mjs
