
name: Move Issues by Date TEST
on: 
  schedule: 
    - cron: '0 16 * * *' # Exécute tous les jours à 16h
  workflow_dispatch:
jobs:
  move_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '18'
      - name: Install dependencies
        run: npm install @octokit/rest
      - name: Create move_issues.mjs
        run: |
          echo "import { Octokit } from '@octokit/rest';
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function moveIssues() {
            console.log('Fetching issues...');
            const issues = await octokit.issues.listForRepo({
              owner: process.env.GITHUB_OWNER,
              repo: process.env.GITHUB_REPO,
              state: 'open'
            });
            console.log('Issues fetched:', issues.data.length);
            const projectColumns = await octokit.projects.listColumns({
              project_id: process.env.PROJECT_ID
            });
            const doneColumn = projectColumns.data.find(column => column.name === 'Terminé');
            if (!doneColumn) {
              console.error('Terminé column not found');
              return;
            }
            const today = new Date();
            for (const issue of issues.data) {
              console.log('Processing issue:', issue.number);
              const match = issue.body.match(/Date de fermeture: (\d{4}-\d{2}-\d{2})/);
              if (match) {
                const closeDate = new Date(match[1]);
                console.log('Close date:', closeDate);
                if (closeDate < today) {
                  console.log('Moving issue to Terminé column:', issue.number);
                  await octokit.projects.moveCard({
                    card_id: issue.id,
                    column_id: doneColumn.id,
                    position: 'top'
                  });
                }
              }
            }
          }

          moveIssues();" > move_issues.mjs
      - name: Run move_issues.mjs
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: 'Exo-create'
          GITHUB_REPO: 'Classe-Informatique-I.FDA-P1A-'
          PROJECT_ID: '9'  # Remplace par l'ID réel de ton projet
        run: node move_issues.mjs
